openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'copy api'
  description: 'monitor sever, trade server, user app 과 DB 사이의 REST API'

servers:
  - description: "프로젝트 local dev server"
    url : http://127.0.0.1:3000/api
  - description : "프로젝트 원격 test server"
    url : http://124.50.247.56:3000/api
  
paths:
  /test/LT_info:
    get:
      summary : "leader trader 정보 테이블 조회 테스트"
      description : "leader trader 정보 테이블 조회 테스트용 api, 테이블 전체 json 데이터를 불러옴"
      tags:
        - Test api 
      responses:
        '200':
          description : "정상 응답, DB 정상 작동중"
          content:
            application/json:
              schema:
              type:
              itmes:
              type:
        '404':
          description : "DB 접속에러"
              

  /test/LT_history:
    get:
      summary : "leader trader 거래 정보 테이블 조회 테스트"
      description : "leader trader 거래 정보 테이블 조회 테스트용 api, 테이블 전체 json 데이터를 불러옴"
      tags:
        - Test api 
      responses:
        '200':
          description : "정상 응답, DB 정상 작동중"
          content:
            application/json:
              schema:
              type:
              itmes:
              type:
        '404':
          description : "DB 접속에러"
